import os
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import smtplib

email_address = "gamingabdou467@gmail.com"
password = "ccpr kopo wtoh jsni"

def send_folder(folder_path, toaddr):

    msg = MIMEMultipart()
    msg['From'] = email_address
    msg['To'] = toaddr
    msg['Subject'] = "Files Folder Output"

    msg.attach(MIMEText("Here are the files generated by the program.", 'plain'))

    # Attach every file in the folder
    for filename in os.listdir(folder_path):
        filepath = os.path.join(folder_path, filename)

        if os.path.isfile(filepath):
            with open(filepath, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())

            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename={filename}"
            )
            msg.attach(part)

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(email_address, password)
    server.sendmail(email_address, toaddr, msg.as_string())
    server.quit()
